services:
  dasharr:
    image: schenanigans/dasharr:0.5.45
    container_name: dasharr
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ=America/New_York  # Change to your timezone
      - PUID=1000
      - PGID=1000
      # - DASHARR_SELF_SIGNED=false  # Uncomment to require valid TLS certificates