services:
  dasharr:
    image: schenanigans/dasharr:latest
    container_name: dasharr
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
